volumes:
    vol_dados:
services:
    www:
        build: .
        ports:
            - "8080:80"
        volumes:
            - ./app:/var/www/html/
        links: 
            - mysql
        networks:
            - default
    mysql:
        image: mysql:8.3.0
        #command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: bd_yii
            MYSQL_ROOT_PASSWORD: rootpass
        volumes:
            - ./bd:/docker-entrypoint-initdb.d
            - vol_dados:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin:5.2.1
        links: 
            - mysql:db
        ports:
            - 82:80
        environment:
            MYSQL_ROOT_PASSWORD: rootpass